### ISSUE TITLE
Rubygems "Homepage" link is incorrect

### ISSUE THREAD

**Issue by tiegz** [tablecheck/dartsass-sprockets#12]
The "Homepage" link on [rubygems](https://rubygems.org/gems/dartsass-sprockets) points to [https://github.com/sass/dartsass-sprockets](https://github.com/sass/dartsass-sprockets) instead of [https://github.com/tablecheck/dartsass-sprockets](https://github.com/tablecheck/dartsass-sprockets)

**Comment by johnnyshields** [comment]
Thanks for heads up. That was fixed here https://github.com/tablecheck/dartsass-sprockets/pull/4/files and will be updated next time we push a gem.
